// ============================================================
// CURRY CLUB DATA — Extracted from WhatsApp Chat History
// ============================================================
// Images: drop photos into "images/" folder and update the
// image field, e.g. "images/pride-of-sylhet.jpg"
//
// NOTE: Ratings are based on John's scoring from the chat.
// Where no explicit rating was given, a best estimate is used
// based on the group's comments. Adjust as you see fit!
// ============================================================

const curryNights = [
  {
    id: 1,
    name: "Pride of Sylhet",
    location: "Great Dunmow",
    date: "2021-10-15",
    organiser: "John Garrett",
    pub: "The Chequers",
    rating: 4,
    comment: "The very first curry club meeting. Bar set very high from the start. Pete nearly missed it due to child collection logistics.",
    image: "images/IMG-20211015-WA0000.jpg"
  },
  {
    id: 2,
    name: "Rose of India",
    location: "Chelmsford",
    date: "2021-11-12",
    organiser: "Wodge",
    pub: "The Ship",
    rating: 4,
    comment: "Very yummy curry house, 9/10. Wodge drove because of an early start. Pete bailed again — his secretary needs sacking.",
    image: "images/IMG-20211112-WA0001.jpg",
    images: ["images/IMG-20211112-WA0001.jpg","images/IMG-20211112-WA0002.jpg"]
  },
  {
    id: 3,
    name: "Razza",
    location: "Felsted",
    date: "2021-12-17",
    organiser: "Pete Chalklen",
    pub: "The Swan",
    rating: 4,
    comment: "The Christmas special. Pete organised Chequers and Razza. Christmas jumpers were encouraged. Andy had a sore head the next morning. Wodge was sweating Dopiaza.",
    image: "images/IMG-20211215-WA0000.jpg",
    images: ["images/IMG-20211215-WA0000.jpg","images/IMG-20211215-WA0001.jpg","images/IMG-20211215-WA0002.jpg"]
  },
  {
    id: 4,
    name: "Ruby",
    location: "Bishops Stortford",
    date: "2022-01-21",
    organiser: "Andy Bott",
    pub: "The Cock Inn",
    rating: 4,
    comment: "Interesting pub and quality meal. Good work Mr Bott. Louise provided taxi service there, cab back from the station.",
    image: "images/IMG-20220121-WA0001.jpg",
    images: ["images/IMG-20220121-WA0001.jpg"]
  },
  {
    id: 5,
    name: "Voujon",
    location: "Rayne",
    date: "2022-02-11",
    organiser: "John Garrett",
    pub: "The Swan / Welsh Princess",
    rating: 4,
    comment: "Pete missed it due to Covid despite 3 jabs. The remaining lads had a cobra for him. Really yummy food.",
    image: "images/IMG-20220211-WA0002.jpg",
    images: ["images/IMG-20220211-WA0002.jpg","images/IMG-20220211-WA0003.jpg","images/IMG-20220211-WA0004.jpg"]
  },
  {
    id: 6,
    name: "Raj Garden",
    location: "White Notley",
    date: "2022-03-11",
    organiser: "Wodge",
    pub: "None nearby",
    rating: 3,
    comment: "Exclusive use of the restaurant — private dining experience for three. Straight to the Indian, no pub next door.",
    image: null
  },
  {
    id: 7,
    name: "Balti Spice",
    location: "Great Dunmow",
    date: "2022-04-29",
    organiser: "Andy Bott",
    pub: "Local Dunmow pub",
    rating: 4,
    comment: "Stephen Brazier's first curry club appearance. Excellent effort from Mr Bott. Bus there, bus back — if they didn't get locked in the curry house.",
    image: "images/IMG-20220427-WA0001.jpg"
  },
  {
    id: 8,
    name: "Bombay Butler",
    location: "Stansted Mountfitchet",
    date: "2022-05-20",
    organiser: "Stephen Brazier",
    pub: "Kings Arms",
    rating: 1,
    comment: "Stephen booked it in 'Takley' — Andy's sources confirmed it was Stansted Mountfitchet. Stephen drove as he wasn't in the right frame of mind to drink. Legend status: 1 star.",
    image: null
  },
  {
    id: 9,
    name: "Lounge India",
    location: "Braintree",
    date: "2022-06-24",
    organiser: "John Garrett",
    pub: "The Picture Palace",
    rating: 4,
    comment: "A good one not to be missed. Pete made a rare appearance. Table booked for 5 — the gang was back together.",
    image: "images/IMG-20220624-WA0000.jpg"
  },
  {
    id: 10,
    name: "Jalsa Ghar",
    location: "Great Dunmow",
    date: "2022-08-05",
    organiser: "Wodge",
    pub: "Not Applicable",
    rating: 3,
    comment: "Originally planned for Thaxted but transport issues meant a local pivot. Wodge celebrated becoming self-employed with a celebratory beer or two.",
    image: "images/IMG-20220805-WA0000.jpg"
  },
  {
    id: 11,
    name: "Star of India",
    location: "Thaxted",
    date: "2022-09-23",
    organiser: "Andy Bott",
    pub: "Local Thaxted pub",
    rating: 3,
    comment: "Andy drove the crew to the lovely village of Thaxted. Wodge cried off with a mystery virus — sweating 7-8 litres a day. A beer was had in his honour.",
    image: "images/IMG-20220923-WA0001.jpg"
  },
  {
    id: 12,
    name: "Pride of Sylhet",
    location: "Great Dunmow",
    date: "2022-10-20",
    organiser: "John Garrett",
    pub: "The Chequers",
    rating: 4,
    comment: "The 1 year anniversary! John declared October meetings would always be at the POS in Dunmow. A tradition was born.",
    image: "images/IMG-20221018-WA0000.jpg",
    images: ["images/IMG-20221018-WA0000.jpg","images/IMG-20221020-WA0000.jpg","images/IMG-20221020-WA0003.jpg","images/IMG-20221020-WA0004.jpg","images/IMG-20221020-WA0005.jpg"]
  },
  {
    id: 13,
    name: "Astare (Turkish)",
    location: "Witham",
    date: "2022-11-26",
    organiser: "Wodge",
    pub: "Battlesford Court",
    rating: 3,
    comment: "A one-off change in proceedings — Turkish instead of Indian due to a glut of curries. Fun fact: Witham had 34 pubs in the 90s.",
    image: null
  },
  {
    id: 14,
    name: "Pride of Sylhet",
    location: "Great Dunmow",
    date: "2022-12-23",
    organiser: "Andy Bott",
    pub: "The Chequers",
    rating: 4,
    comment: "Christmas meeting back at the POS. Onion bhaji appreciation was a prerequisite of entry.",
    image: "images/IMG-20221223-WA0001.jpg",
    images: ["images/IMG-20221223-WA0001.jpg","images/IMG-20221223-WA0002.jpg","images/IMG-20221223-WA0003.jpg"]
  },
  {
    id: 15,
    name: "Spice Lounge",
    location: "Great Baddow",
    date: "2023-01-20",
    organiser: "Wodge",
    pub: "The Star",
    rating: 5,
    comment: "A new 5 star restaurant! Good work Rog! It lived up to its promise — good to have fire again. Stephen made it back on his feet.",
    image: null
  },
  {
    id: 16,
    name: "Taj Mahal",
    location: "Braintree",
    date: "2023-02-10",
    organiser: "John Garrett",
    pub: "The Eagle",
    rating: 4,
    comment: "You can really taste the 5 stars for hygiene. John was accused of treason for going without the full crew.",
    image: "images/IMG-20230210-WA0000.jpg"
  },
  {
    id: 17,
    name: "Pakwaan",
    location: "Braintree",
    date: "2023-02-24",
    organiser: "Taylor Hickson",
    pub: "The Eagle",
    rating: 2.5,
    comment: "Taylor's debut as organiser. Naan breads inedible, no tablecloths, no music, slow service. John tried hard for a 3 but couldn't do it. Taylor called it totally unfair.",
    image: null,
    images: []
  },
  {
    id: 18,
    name: "Cafe Masala",
    location: "Bishops Stortford",
    date: "2023-03-17",
    organiser: "John Garrett",
    pub: "The Cock Inn",
    rating: 3,
    comment: "Return trip to Cafe Masala. Taylor was at Sadler Towers. Stephen made it along this time.",
    image: null,
    images: []
  },
  {
    id: 19,
    name: "The Coriander",
    location: "Ongar",
    date: "2023-04-28",
    organiser: "Andy Bott",
    pub: "The Cock",
    rating: 4.5,
    comment: "Clear winner — Pete would even take the family. Tablecloths available upon request. The Knobs Creek may have come at a cost. Half star docked for unwelcome post-curry considerations.",
    image: "images/IMG-20230428-WA0001.jpg",
    images: ["images/IMG-20230428-WA0001.jpg"]
  },
  {
    id: 20,
    name: "Cinnamon Tree",
    location: "Halstead",
    date: "2023-05-12",
    organiser: "Taylor Hickson",
    pub: "The White Hart Inn",
    rating: 3,
    comment: "A sombre evening — Andy's mum passed away that morning. The remaining three carried on in his honour. Scores to follow.",
    image: "images/IMG-20230512-WA0000.jpg",
    images: ["images/IMG-20230512-WA0000.jpg","images/IMG-20230513-WA0000.jpg"]
  },
  {
    id: 21,
    name: "Yuva",
    location: "Debden",
    date: "2023-06-23",
    organiser: "Wodge",
    pub: "The Plough",
    rating: 3,
    comment: "The original venue shut down days before the booking. Wodge pivoted to Yuva. A strawberry daiquiri made its curry club debut. Shame about the rum.",
    image: "images/IMG-20230623-WA0001.jpg",
    images: ["images/IMG-20230623-WA0001.jpg","images/IMG-20230624-WA0001.jpg","images/IMG-20230624-WA0006.jpg"]
  },
  {
    id: 22,
    name: "Zara Dining",
    location: "Bishops Stortford",
    date: "2023-07-14",
    organiser: "John Garrett",
    pub: "The White Horse",
    rating: 4,
    comment: "All talk of a Gurkha's Revenge amounted to nothing. Taylor was on shift so missed out. Pete's dad had a new hip but Pete still made it.",
    image: "images/IMG-20230714-WA0000.jpg",
    images: ["images/IMG-20230714-WA0000.jpg","images/IMG-20230714-WA0001.jpg"]
  },
  {
    id: 23,
    name: "Bombay Spice",
    location: "Stansted Mountfitchet",
    date: "2023-09-22",
    organiser: "Andy Bott",
    pub: "The Queens Head",
    rating: 3,
    comment: "Revisiting Stansted Mountfitchet. Andy was still deciding location the day before. Table booked for 8pm, pickup at 7:15.",
    image: "images/IMG-20230922-WA0000.jpg"
  },
  {
    id: 24,
    name: "Shadhona",
    location: "Bishops Stortford",
    date: "2023-10-13",
    organiser: "Taylor Hickson",
    pub: "The Port Jackson",
    rating: 3.5,
    comment: "Good effort from Taylor. John tried Korean the night before and declared it nowhere near as good as curry. Roger is in the chair for November.",
    image: "images/IMG-20231012-WA0001.jpg",
    images: ["images/IMG-20231012-WA0001.jpg","images/IMG-20231014-WA0003.jpg"]
  },
  {
    id: 25,
    name: "Cinnamon",
    location: "Epping",
    date: "2023-11-10",
    organiser: "Wodge",
    pub: "The George & Dragon",
    rating: 4,
    comment: "A cracking 4 star Epping-based restaurant. Here's to you, The Coriander. John was sitting by the door with shoes and coat on, ready whenever.",
    image: "images/IMG-20231110-WA0001.jpg",
    images: ["images/IMG-20231110-WA0001.jpg","images/IMG-20231111-WA0000.jpg"]
  },
  {
    id: 26,
    name: "Cinnamon, Brick Lane",
    location: "London (Brick Lane)",
    date: "2023-12-15",
    organiser: "John Garrett",
    pub: "Various London pubs",
    rating: 4,
    comment: "The Christmas special in London! F1 Arcade racing at St Paul's first, then Brick Lane. Absolute chaos of an experience. John tested all week — no FIA constraints.",
    image: "images/IMG-20231214-WA0000.jpg",
    images: ["images/IMG-20231214-WA0000.jpg","images/IMG-20231215-WA0000.jpg","images/IMG-20231215-WA0001.jpg","images/IMG-20231215-WA0002.jpg","images/IMG-20231215-WA0003.jpg","images/IMG-20231215-WA0005.jpg","images/IMG-20231215-WA0006.jpg","images/IMG-20231215-WA0007.jpg","images/IMG-20231215-WA0008.jpg"]
  },
  {
    id: 27,
    name: "Shahjan Tandoori",
    location: "Chelmsford",
    date: "2024-01-19",
    organiser: "Andy Bott",
    pub: "Nags Head",
    rating: 4,
    comment: "Mystery location — exciting! A great January meeting, a great choice from Andy. Taylor to come up with something for Feb.",
    image: "images/IMG-20240119-WA0000.jpg",
    images: ["images/IMG-20240119-WA0000.jpg"]
  },
  {
    id: 28,
    name: "The Onion Bhaji",
    location: "Sudbury",
    date: "2024-02-09",
    organiser: "Taylor Hickson",
    pub: "The Cock & Bell",
    rating: 4,
    comment: "An amazing upturn in form from Taylor! Great food and a personal pun on the name. Ironically the onion bhajis at The Onion Bhaji let them down a little.",
    image: "images/IMG-20240209-WA0000.jpg",
    images: ["images/IMG-20240209-WA0000.jpg","images/IMG-20240209-WA0001.jpg"]
  },
  {
    id: 29,
    name: "Anwar's Exquisite Indian",
    location: "Hatfield Heath",
    date: "2024-03-01",
    organiser: "Wodge",
    pub: "Local pub",
    rating: 4.5,
    comment: "Pete made a rare appearance and drove! Cracking night — hadn't laughed so much in ages. Good pub, welcoming bar staff, calming 80s ballads and Sheryl the part-time Asda checkout lady who likes a sing song.",
    image: "images/IMG-20240301-WA0000.jpg",
    images: ["images/IMG-20240301-WA0000.jpg"]
  },
  {
    id: 30,
    name: "Chandini Indian",
    location: "Sawbridgeworth",
    date: "2024-04-26",
    organiser: "Taylor Hickson",
    pub: "The Rising Sun",
    rating: 3.5,
    comment: "Added to the Sadlers novelty curry restaurant desert bowl hall of fame. Andy drove as John had no car.",
    image: "images/IMG-20240426-WA0000.jpg",
    images: ["images/IMG-20240426-WA0000.jpg","images/IMG-20240426-WA0002.jpg"]
  },
  {
    id: 31,
    name: "Merchant Spice",
    location: "Braintree",
    date: "2024-06-08",
    organiser: "Andy Bott",
    pub: "Legends (Braintree)",
    rating: 4,
    comment: "Legends in Braintree from 4pm for pre-curry fun, then curry at 7:45. Pineapple daiquiris on the menu. Variety is the spice of life.",
    image: "images/IMG-20240609-WA0000.jpg",
    images: ["images/IMG-20240609-WA0000.jpg","images/IMG-20240609-WA0001.jpg"]
  },
  {
    id: 32,
    name: "Pride of Sylhet",
    location: "Great Dunmow",
    date: "2024-08-02",
    organiser: "John Garrett",
    pub: "The Chequers",
    rating: 3,
    comment: "Back to basics with an old favourite. Lou drove. Tried to visit the Chequers again as Andy had never been. Buses back at 10:30 or 12:30.",
    image: "images/IMG-20240802-WA0000.jpg",
    images: ["images/IMG-20240802-WA0000.jpg","images/IMG-20240803-WA0000.jpg"]
  },
  {
    id: 33,
    name: "Maldon Spice",
    location: "Maldon",
    date: "2024-09-13",
    organiser: "Taylor Hickson",
    pub: "Black Rabbit",
    rating: 3,
    comment: "Taylor took the crew to the bright lights and exotic music of Maldon high street. 3 stars with a broken freezer.",
    image: null
  },
  {
    id: 34,
    name: "Lounge India",
    location: "Chelmsford",
    date: "2024-10-25",
    organiser: "Andy Bott",
    pub: "Not Applicable",
    rating: 4,
    comment: "Food was good. Trip Advisor slated the onion bhaji starter as the smallest ever served. The lads needed to check if they do big balls.",
    image: "images/IMG-20241025-WA0004.jpg",
    images: ["images/IMG-20241025-WA0004.jpg"]
  },
  {
    id: 35,
    name: "Maria's",
    location: "Coggeshall Hamlet",
    date: "2024-11-22",
    organiser: "Wodge",
    pub: "White Hart",
    rating: 3.5,
    comment: "Pete was at the cinema with Katie. John noted 11 restaurants visited in 2024, about 425 miles covered. No real standout winner but plenty of 4 star reviews.",
    image: "images/IMG-20241122-WA0002.jpg",
    images: ["images/IMG-20241122-WA0002.jpg"]
  },
  {
    id: 36,
    name: "Bengal Tiger",
    location: "London (Old Street, Shoreditch)",
    date: "2024-12-13",
    organiser: "John Garrett",
    pub: "Liverpool Street pubs",
    rating: 4,
    comment: "Award-winning Christmas curry in Shoreditch. Good night with no Stella distractions. Andy made it to Heathrow on time the next morning. Best Xmas one to date.",
    image: "images/IMG-20241213-WA0000.jpg",
    images: ["images/IMG-20241213-WA0000.jpg","images/IMG-20241214-WA0000.jpg","images/IMG-20241214-WA0001.jpg","images/IMG-20241214-WA0002.jpg","images/IMG-20241214-WA0003.jpg","images/IMG-20241214-WA0004.jpg"]
  },
  {
    id: 37,
    name: "Maldon Tandoori",
    location: "Maldon",
    date: "2025-01-31",
    organiser: "Taylor Hickson",
    pub: "Rose & Crown",
    rating: 2.5,
    comment: "Another trip to Maldon. Tablecloths and cock rings but service and food was lacking and expensive. Purple hair and care-home stories was a nice change of pace.",
    image: null,
    images: []
  },
  {
    id: 38,
    name: "Pride of Sylhet",
    location: "Great Dunmow",
    date: "2025-02-22",
    organiser: "John Garrett",
    pub: "Saracens Head",
    rating: 3,
    comment: "A medical exemption took them to Dunmow. John forced Andy to watch rugby all afternoon. Third visit to the POS — fun but food was pretty average.",
    image: null,
    images: []
  },
  {
    id: 39,
    name: "Wadud I&T Fusion",
    location: "Bradwell",
    date: "2025-03-28",
    organiser: "Andy Bott",
    pub: "Mulberry Tree",
    rating: 3.5,
    comment: "Pete skipped for a 20-mile run the next morning. He misses the lads though.",
    image: "images/IMG-20250328-WA0001.jpg"
  },
  {
    id: 40,
    name: "The Gurkha Restaurant",
    location: "Chelmsford",
    date: "2025-05-23",
    organiser: "John Garrett",
    pub: "The Ship",
    rating: 3.5,
    comment: "John booked a table hoping it's a good 'un. Vijay Mallya apparently approves.",
    image: "images/IMG-20250523-WA0001.jpg"
  },
  {
    id: 41,
    name: "Mowgli Street Food",
    location: "Chelmsford",
    date: "2025-06-13",
    organiser: "Taylor Hickson",
    pub: "The Golden Fleece",
    rating: 3,
    comment: "Taylor accidentally booked the same place from July 2023. Had to rebook another — all good in the end. Pete was in Wales.",
    image: "images/IMG-20250611-WA0002.jpg",
    images: ["images/IMG-20250611-WA0002.jpg"]
  },
  {
    id: 43,
    name: "Curry & Cocktails",
    location: "Chelmsford",
    date: "2025-09-26",
    organiser: "Andy Bott",
    pub: "Wheatsheaf",
    rating: 4,
    comment: "Excellent choice from Andy — really enjoyed some South Indian curry for a change. And no dodgy tummy either!",
    image: null,
    images: []
  },
  {
    id: 44,
    name: "Kelvedon Spice",
    location: "Kelvedon",
    date: "2025-10-24",
    organiser: "Wodge",
    pub: "Angel",
    rating: 3.5,
    comment: "On the high street in Kelvedon. Stephen Brazier made a comeback. Wodge booked for one extra as he had a sixth sense about late takers.",
    image: null
  },
  {
    id: 45,
    name: "Cinnamon",
    location: "North Weald",
    date: "2025-11-21",
    organiser: "John Garrett",
    pub: "Kings Head",
    rating: 3.5,
    comment: "John booked both Nov and Dec restaurants from his sick bed. Then flew to Warsaw for the weekend.",
    image: "images/IMG-20251121-WA0001.jpg"
  },
  {
    id: 46,
    name: "The India",
    location: "London",
    date: "2025-12-19",
    organiser: "John Garrett",
    pub: "Cross Keys",
    rating: 3.5,
    comment: "2025 Christmas meeting. Shah giggled at Andy's order. Solid 3.5 from Wodge (docked 0.5 for tempting him with sticky toffee pudding then ruining Christmas). Andy raised it to 4. Looking at you, Mowgli.",
    image: null
  },
  {
    id: 47,
    name: "Omar's Tandoori",
    location: "Hatfield Peveral",
    date: "2026-01-16",
    organiser: "Andy Bott",
    pub: "Duke of Wellington",
    rating: 3,
    comment: "Jeff joined as a new member. Can't maintain a 4 star run forever! Full history screenshot shared for new members' interest.",
    image: "images/IMG-20260119-WA0002.jpg",
    images: ["images/IMG-20260119-WA0002.jpg","images/IMG-20260119-WA0003.jpg","images/IMG-20260119-WA0004.jpg"],
    attendees: ["John Garrett","Wodge","Andy Bott","Stephen Brazier","Taylor Hickson"]
  },
  {
    id: 48,
    name: "Zara Indian Cuisine",
    location: "Danbury",
    date: "2026-02-27",
    organiser: "Taylor Hickson",
    pub: "The Anchor",
    rating: 4,
    comment: "Jeff called it a good start with a solid 4 star curry. Taylor squeezed everyone in. Well done Taylor.",
    image: "images/IMG-20260227-WA0003.jpg",
    attendees: ["John Garrett","Wodge","Andy Bott","Taylor Hickson","Jeff"]
  },
  {
    id: 49,
    name: "Pakwaan",
    location: "Writtle",
    date: "2026-03-13",
    organiser: "Wodge",
    pub: "Rose & Crown, Wheatsheaf",
    rating: 4,
    comment: "Fanciest onion bhaji ever. Personal touch from the chef, pink-haired dancing girls, high-end drinks, variety of desserts. Lost a club member and had a lock-in at the locals' choice. But they had to pay for it!",
    image: "images/IMG-20260313-WA0003.jpg",
    images: ["images/IMG-20260313-WA0003.jpg","images/IMG-20260313-WA0004.jpg","images/IMG-20260313-WA0005.jpg"],
    attendees: ["John Garrett","Wodge","Andy Bott","Taylor Hickson","Jeff"]
  },
  {
    id: 50,
    name: "Dosa Paratha Corner",
    location: "Saffron Walden",
    date: "2025-04-17",
    organiser: "Wodge",
    pub: "Maypole",
    rating: 3,
    comment: "Quite Niche",
    image: null
  },
  {
    id: 51,
    name: "The Mogul",
    location: "Ongar",
    date: "2026-04-24",
    organiser: "John Garrett",
    pub: "The Cock Tavern",
    rating: 4.5,
    comment: "Rating: 4.5/5 | Quite opinionated | Attendees: 6\n\nHaving tried the competition on the high street, it was now The Mogul's turn. We were seated promptly in the centre of the room and got the drinks in: Cobras for the passengers, Cokes for the drivers.\n\nTHE FOOD: We started with thin, crisp poppadoms, onion salad and a decent mango chutney. The menu is genuinely interesting, featuring plenty of dishes we'd never encountered. The staff were attentive too, keeping a close eye on our glasses. They even sent over complimentary starters: chicken wings and corn ribs with a spicy dressing. The wings were perfectly nice, but the corn ribs were fantastic. Before the mains, the kitchen brought out two specials with roti. While the chicken was good, the beef curry was the absolute highlight — rare to see beef on an Indian menu, and far too good to be tucked away on a nondescript specials board.\n\nTHE MAINS: Rezala, Methi, and Rizoti — all brand new to us and impressive. Duck Kormari served in a tangy mushroom gravy. Bengal Biryani arrived under a massive pie crust, so substantial the diner had to take half home for tomorrow's lunch. Onion Bhajis — an essential test for our group, and these didn't disappoint. Excellent.\n\nDESSERT & BILL: We had no room left for dessert, which was a shame as the options looked far better than the standard frozen sorbets left over from the last ice age. The bill was very reasonable. We added an extra 10% on top of the service charge to reflect the generous complimentary dishes.\n\nFINAL THOUGHT: The restaurant clearly looked at our order and decided we were missing out on their best dishes. A great meal, some lively conversation, a new member and another enjoyable evening.",
    image: null,
    attendees: ["John Garrett","Wodge","Andy Bott","Taylor Hickson","Jeff","Big Guy (Stu)"]
  },
  {
    id: 52,
    name: "Tanishq Restaurant & Bar",
    location: "Toot Hill Golf Club, Ongar",
    date: "2026-05-22",
    organiser: "Jeff",
    pub: "Green Man",
    rating: 4.5,
    comment: "My first booking, and have to say pretty pleased, a great start, food with real gold, a selection of deserts as good as I've ever had anywhere, and not just chocolates to finish, cubes of cheesecake, really hard to fault, only deductions food could have been hotter, and loss of authentic atmosphere, but a strong 4.5+ for me, would definitely go again, one for date night",
    image: "images/Tanishq_ongar.jpg",
    images: ["images/Tanishq_ongar.jpg","images/Tanishq_2nd.jpeg"],
    attendees: ["John Garrett","Wodge","Andy Bott","Jeff"]
  },
  {
    id: 53,
    name: "Tandoori Cottage",
    location: "Bishops Stortford",
    date: "2026-06-12",
    organiser: "Andy Bott",
    pub: "Jolly Brewers",
    rating: 2.5,
    comment: "Tucked away in a mysterious corner of Bishop\u2019s Stortford \u2014 a part I\u2019m fairly sure wasn\u2019t on any map \u2014 we found Tandoori Cottage hiding among business units, sporting a sign so subtle it was practically playing hide\u2011and\u2011seek. At least the pub was only a two\u2011minute stroll away, which felt like a reassuring anchor to civilisation.\n\nInside, the d\u00e9cor was surprisingly smart, and the bar setup looked ready for a much livelier crowd than the grand total of two other diners we saw all night. The food itself was genuinely good\u2026 but dessert? Let\u2019s just say my strawberry cheesecake was so fresh from the freezer it still had its wrapper on. A bold choice.\n\nPrices were reasonable, but the finale was memorable for all the wrong reasons: no card machine, no cash \u2014 instead, we were handed bank details on a scrap of paper and asked to do a transfer. Very cloak\u2011and\u2011dagger.\n\nOverall, the food carried the night, but everything else felt a bit surreal. A solid 2.5 seems fair.",
    image: null,
    attendees: ["John Garrett","Wodge","Andy Bott"]
  }
];
